_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
